---
openapi: 3.0.0
info:
  title: Modern LMS Stater API
  description: REST API for LMS Server Microservice Development
  version: 0.0.1

servers:
  - url: ''
tags:
  - name: demo-user
    description: Starter Demo User Service
  - name: discovery
    description: Service Discovery services
paths:
  ##################################################
  # Service Discovery
  ##################################################
  /discovery/{applicationName}:
    $ref: ./paths/discovery/discovery.yaml#/paths/get_service_instances

#  ##################################################
#  # Demo User Service
#  ##################################################
  /demoUser/findAllUsers:
    $ref: ./paths/demo/demo.yaml#/paths/find_all
#
#  ##################################################
#  # Dummy Endpoint to trigger model generation
#  ##################################################
  /modelGen/pleaseIgnoreMe:
    $ref: ./paths/model/model.yaml#/paths/root
