image: docker:latest
services:
  - docker:18-dind

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
    - if: $CI_COMMIT_BRANCH == "master"

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  before_script:
    - echo $REVIEW_APP_URL
    - echo $SPRING_PROFILES_ACTIVE
    - echo "docker login $CI_REGISTRY -u $CI_DEPLOY_USER"
  script:
    - echo "mvn install -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE -Dspring.application.name=$SPRING_APPLICATION_NAME -Dspring.cloud.config.uri=$SPRING_CLOUD_CONFIG_URI -Dservice.discovery.uri=$SERVICE_DISCOVERY_URI"
    - "mvn install -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE -Dspring.application.name=$SPRING_APPLICATION_NAME -Dspring.cloud.config.uri=$SPRING_CLOUD_CONFIG_URI -Dservice.discovery.uri=$SERVICE_DISCOVERY_URI"
  artifacts:
    paths:
      - target/app.jar
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

docker-build:
  stage: package
  script:
    - docker login $CI_REGISTRY -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

k8s-deploy-staging:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy
  dependencies:
    - docker-build
  script:
    - kubectl config set-cluster k8s --server="$CLUSTER_ADDRESS"
    - kubectl config set clusters.k8s.certificate-authority-data $CLUSTER_CA_AUTH_DATA
    - kubectl config set-credentials gitlab-service-account --token=$K8S_TOKEN
    - kubectl config set-context default --cluster=k8s --user=gitlab-service-account --namespace=staging
    - kubectl config use-context default
    - kubectl delete secret $CI_REGISTRY --ignore-not-found
    - kubectl delete -f deployment.yml --namespace=staging --ignore-not-found
    - kubectl create secret docker-registry $CI_REGISTRY --docker-server=https://$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD --docker-email=$GITLAB_USER_EMAIL
    - kubectl apply -f deployment.yml --namespace=staging
  environment:
    name: staging
    url: $REVIEW_APP_URL
  only:
    - master
