apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter-deployment
  labels:
    app: starter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: starter
  template:
    metadata:
      labels:
        app: starter
    spec:
      containers:
        - name: starter
          image: registry.learnet.io/learnet/starter
          imagePullPolicy: Always
          ports:
            - containerPort: 7080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_APPLICATION_NAME
              value: "starter"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://configserver:8888"
      imagePullSecrets:
        - name: starter.learnet.io
---
apiVersion: v1
kind: Service
metadata:
  name: starter
spec:
  type: ClusterIP
  ports:
    - port: 7080
  selector:
    app: starter