apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: registry.learnet.io/learnet/account
          imagePullPolicy: Always
          ports:
            - containerPort: 7080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_APPLICATION_NAME
              value: "account"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://configserver:8888"
      imagePullSecrets:
        - name: account.learnet.io
---
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  type: ClusterIP
  ports:
    - port: 7080
  selector:
    app: account