version: '3'
services:
  starter:
    container_name: starter
    build: .
    restart: always
    depends_on:
      - servicediscovery
      - configserver
      - apigateway
    links:
      - es01
    networks:
      - lms-docker-network
    environment:
      - SERVICE_DISCOVERY_HOST=servicediscovery
      - SERVICE_DISCOVERY_PORT=8761
      - CONFIG_SERVER_HOST=configserver
      - CONFIG_SERVER_PORT=8888
      - API_GATEWAY_HOST=apigateway
      - API_GATEWAY_PORT=8080
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=starter
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - DB_HOST=postgres_starter
      - DB_PORT:5432
      - ELASTICSEARCH_HOST=es01
      - ELASTICSEARCH_PORT=9200

networks:
  lms-docker-network:
    driver: bridge